# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cocopod_integration_testTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocopod_integration_test
  pod 'Alamofire', '4.7'

end
